create database if not exists CorujaDB;
use CorujaDB;

CREATE TABLE STATUS_CONTRATO (
  CODSTATUS_CONTRATO int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO          varchar(100) NOT NULL UNIQUE, 
  PRIMARY KEY (CODSTATUS_CONTRATO));
CREATE TABLE CONTRATO (
  CODCONTRATO        int(10) NOT NULL AUTO_INCREMENT, 
  DATA_EMISSAO       date NOT NULL, 
  DATA_CANCELAMENTO  date, 
  CODRESPONSAVEL     int(10) NOT NULL, 
  CODSTATUS_CONTRATO int(10) NOT NULL, 
  PRIMARY KEY (CODCONTRATO));
CREATE TABLE LIVRO (
  CODLIVRO  int(10) NOT NULL AUTO_INCREMENT, 
  DESCRICAO varchar(255) NOT NULL UNIQUE, 
  CODSERIE  int(10) NOT NULL, 
  PRIMARY KEY (CODLIVRO));
CREATE TABLE SERIE (
  CODSERIE int(10) NOT NULL AUTO_INCREMENT, 
  NOME     varchar(255) NOT NULL UNIQUE, 
  PRECO    numeric(19, 2) NOT NULL, 
  PRIMARY KEY (CODSERIE));
CREATE TABLE PESSOA (
  CODPESSOA int(10) NOT NULL AUTO_INCREMENT, 
  NOME      varchar(255) NOT NULL, 
  FONE      varchar(15), 
  EMAIL     varchar(255), 
  CPF       varchar(14) NOT NULL UNIQUE, 
  SEXO      char(1) NOT NULL, 
  PRIMARY KEY (CODPESSOA));
CREATE TABLE ALUNO (
  CODALUNO       int(10) NOT NULL AUTO_INCREMENT, 
  NOME           varchar(255) NOT NULL, 
  ENDERECO       varchar(255) NOT NULL, 
  BAIRRO         varchar(255) NOT NULL, 
  CIDADE         varchar(255) NOT NULL, 
  UF             varchar(2) NOT NULL, 
  DT_NASCIMENTO  date NOT NULL, 
  FONE           varchar(15) NOT NULL, 
  EMAIL          varchar(255), 
  CODRESPONSAVEL int(10) NOT NULL, 
  CODPAI         int(10), 
  CODMAE         int(10), 
  CODSERIE       int(10) NOT NULL, 
  PRIMARY KEY (CODALUNO));
CREATE TABLE RESPONSAVEL (
  CODRESPONSAVEL int(10) NOT NULL AUTO_INCREMENT, 
  NOME           varchar(255) NOT NULL, 
  CPF            varchar(14) NOT NULL UNIQUE, 
  ENDERECO       varchar(255) NOT NULL, 
  BAIRRO         varchar(255) NOT NULL, 
  CIDADE         varchar(255) NOT NULL, 
  CEP            varchar(9) NOT NULL, 
  FONE           varchar(15), 
  EMAIL          int(10), 
  CELULAR        varchar(15), 
  OBSERVACAO     varchar(255), 
  PRIMARY KEY (CODRESPONSAVEL));
ALTER TABLE LIVRO ADD INDEX FKLIVRO423457 (CODSERIE), ADD CONSTRAINT FKLIVRO423457 FOREIGN KEY (CODSERIE) REFERENCES SERIE (CODSERIE);
ALTER TABLE CONTRATO ADD INDEX FKCONTRATO773832 (CODSTATUS_CONTRATO), ADD CONSTRAINT FKCONTRATO773832 FOREIGN KEY (CODSTATUS_CONTRATO) REFERENCES STATUS_CONTRATO (CODSTATUS_CONTRATO);
ALTER TABLE CONTRATO ADD INDEX FKCONTRATO995052 (CODRESPONSAVEL), ADD CONSTRAINT FKCONTRATO995052 FOREIGN KEY (CODRESPONSAVEL) REFERENCES RESPONSAVEL (CODRESPONSAVEL);
ALTER TABLE ALUNO ADD INDEX FKALUNO646995 (CODSERIE), ADD CONSTRAINT FKALUNO646995 FOREIGN KEY (CODSERIE) REFERENCES SERIE (CODSERIE);
ALTER TABLE ALUNO ADD INDEX FKALUNO251451 (CODMAE), ADD CONSTRAINT FKALUNO251451 FOREIGN KEY (CODMAE) REFERENCES PESSOA (CODPESSOA);
ALTER TABLE ALUNO ADD INDEX FKALUNO254338 (CODPAI), ADD CONSTRAINT FKALUNO254338 FOREIGN KEY (CODPAI) REFERENCES PESSOA (CODPESSOA);
ALTER TABLE ALUNO ADD INDEX FKALUNO692290 (CODRESPONSAVEL), ADD CONSTRAINT FKALUNO692290 FOREIGN KEY (CODRESPONSAVEL) REFERENCES RESPONSAVEL (CODRESPONSAVEL);
