ALTER TABLE LIVRO DROP FOREIGN KEY FKLIVRO423457;
ALTER TABLE CONTRATO DROP FOREIGN KEY FKCONTRATO773832;
ALTER TABLE CONTRATO DROP FOREIGN KEY FKCONTRATO995052;
ALTER TABLE ALUNO DROP FOREIGN KEY FKALUNO646995;
ALTER TABLE ALUNO DROP FOREIGN KEY FKALUNO251451;
ALTER TABLE ALUNO DROP FOREIGN KEY FKALUNO254338;
ALTER TABLE ALUNO DROP FOREIGN KEY FKALUNO692290;
DROP TABLE IF EXISTS STATUS_CONTRATO;
DROP TABLE IF EXISTS CONTRATO;
DROP TABLE IF EXISTS LIVRO;
DROP TABLE IF EXISTS SERIE;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS ALUNO;
DROP TABLE IF EXISTS RESPONSAVEL;

