DELETE FROM SERIE;
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (1,'MATERNAL II',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (2,'MATERNAL III',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (3,'NíVEL I',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (4,'NÍVEL II',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (5,'1º EF',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (6,'2º EF',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (7,'3º EF',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (8,'4º EF',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (9,'5º EF',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (10,'6º ANO',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (11,'7º ANO',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (12,'8º ANO',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (13,'9º ANO',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (14,'1º EM',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (15,'2º EM',0);
INSERT INTO SERIE (CODSERIE,NOME, PRECO) VALUES (16,'3º EM',0);

