DELETE FROM SERIE;
INSERT INTO SERIE (CODSERIE,NOME) VALUES (1,'MATERNAL II');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (2,'MATERNAL III');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (3,'NíVEL I');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (4,'NÍVEL II');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (5,'1º EF');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (6,'2º EF');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (7,'3º EF');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (8,'4º EF');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (9,'5º EF');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (10,'6º ANO');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (11,'7º ANO');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (12,'8º ANO');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (13,'9º ANO');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (14,'1º EM');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (15,'2º EM');
INSERT INTO SERIE (CODSERIE,NOME) VALUES (16,'3º EM');

